/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: e113309d50814156742e8767fa25466b)
interface __BaseEnv_Env {
	BOOKS: R2Bucket;
	METRICS: D1Database;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
