/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 38eed8b849dc1374c4923c38ef6556f3)
interface __BaseEnv_Env {
	BOOKS: R2Bucket;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
